theme: jekyll-theme-minimal
description: Egyedi fejlesztésű, teljesen magyar nyelvű, sallangmentes, könnyedén használható tartalom kezelő rendszer. 
use_logo: true
logo: http://kek.trswebdesign.hu/images/logo.png
copyright: 2002-2019 Handzsúr István
breadcrumb_home_name: Start
show_feedback: true
feedback_email: trjoin@gmail.com
