theme: jekyll-theme-minimal
title: KEK CMS
description: Egyedi fejlesztésű, teljesen magyar nyelvű, sallangmentes, könnyedén használható tartalom kezelő rendszer. 
use_logo: true
logo: http://kek.trswebdesign.hu/images/logo.png
